#!/bin/bash
# used some from advanced script to have multiple ports: use an equal number of guest and host ports

echo `date` hook/qemu "${1}" "${2}" >>/root/hook.log

# Update the following variables to fit your setup
Guest_name=Win
Guest_ipaddr=10.1.1.12
Host_ipaddr=192.168.2.20
Host_port=(  ’2181’ ‘9092’)
Guest_port=( ’2181’ ‘9092’)

length=$(( ${#Host_port[@]} - 1 ))
if [ "${1}" = "${Guest_name}" ]; then
   if [ "${2}" = "stopped" ] || [ "${2}" = "reconnect" ]; then
       for i in `seq 0 $length`; do
       done
   fi
   if [ "${2}" = "start" ] || [ "${2}" = "reconnect" ]; then
       for i in `seq 0 $length`; do
               echo "kvm-Hey." >>/root/hook.log
               iptables -t nat -A PREROUTING -d ${Host_ipaddr} -p tcp --dport ${Host_port[$i]} -j DNAT --to ${Guest_ipaddr}:${Guest_port[$i]}
               iptables -I FORWARD -d ${Guest_ipaddr}/32 -p tcp -m state --state NEW,ESTABLISHED,RELATED --dport ${Guest_port[$i]} -j ACCEPT
               iptables -t nat -A PREROUTING -d ${Host_ipaddr} -p udp --dport ${Host_port[$i]} -j DNAT --to ${Guest_ipaddr}:${Guest_port[$i]}
               iptables -I FORWARD -d ${Guest_ipaddr}/32 -p udp -m state --state NEW,ESTABLISHED,RELATED --dport ${Guest_port[$i]} -j ACCEPT
       done
   fi
fi
